language: ruby
rvm:
  - 1.29.1
  - jruby
before_script:
— bundle exec rake db:migrate
— bundle exec rspec
deploy: 
  provider: heroku 
  api_key: ENV['HEROKU_KEY']
  app: rails-test-app-article 
  on : 
    repo: KaterinaVshk/site_clone